# Generated by Django 5.1.3 on 2024-11-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_name', models.CharField(max_length=100)),
                ('head_type', models.CharField(max_length=100)),
                ('itdp_name', models.CharField(max_length=100)),
                ('soes_name', models.CharField(max_length=100)),
                ('sanctioned_budget', models.FloatField()),
                ('revised_estimate', models.FloatField(blank=True, null=True)),
                ('department_code', models.CharField(max_length=50)),
                ('department_name', models.CharField(max_length=100)),
                ('scheme_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
