# Generated by Django 5.1.3 on 2024-11-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_datarow_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarow',
            name='date',
        ),
    ]
