# Generated by Django 5.1.3 on 2024-11-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_datarow_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarow',
            name='id',
        ),
        migrations.AddField(
            model_name='datarow',
            name='unique_id',
            field=models.AutoField(default=34, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datarow',
            name='department_code',
            field=models.CharField(max_length=100),
        ),
    ]
