# Generated by Django 5.1.3 on 2024-11-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_datarow_id_datarow_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarow',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='datarow',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datarow',
            name='unique_search',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
