# Generated by Django 5.1.3 on 2024-11-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_datarow_head_type_remove_datarow_itdp_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarow',
            name='unique_search',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
