# Generated by Django 5.1.3 on 2024-11-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_datarow_unique_search'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datarow',
            unique_together={('department_code', 'department_name')},
        ),
    ]
