# Generated by Django 5.1.3 on 2024-11-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_datarow_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datarow',
            unique_together=set(),
        ),
    ]
