# Generated by Django 5.1.3 on 2024-11-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_datarow_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datarow',
            name='unique_head_name_per_department',
        ),
        migrations.AlterUniqueTogether(
            name='datarow',
            unique_together=set(),
        ),
    ]
