# Generated by Django 5.1.3 on 2024-11-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_datarow_unique_head_name_per_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datarow',
            old_name='soes_name',
            new_name='soe_name',
        ),
        migrations.AddConstraint(
            model_name='datarow',
            constraint=models.UniqueConstraint(fields=('department_code', 'department_name'), name='unique_department_code_name'),
        ),
        migrations.AddConstraint(
            model_name='datarow',
            constraint=models.UniqueConstraint(fields=('head_name', 'department_name'), name='unique_head_department'),
        ),
        migrations.AddConstraint(
            model_name='datarow',
            constraint=models.UniqueConstraint(fields=('soe_name', 'head_name'), name='unique_soe_per_head'),
        ),
    ]
