# Generated by Django 5.1.3 on 2024-11-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_soes_name_datarow_soe_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datarow',
            name='unique_department_code_name',
        ),
    ]
