# Generated by Django 5.1.3 on 2024-11-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_datarow_unique_head_department_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='datarow',
            constraint=models.UniqueConstraint(fields=('scheme_name', 'head_name'), name='unique_scheme_per_head'),
        ),
    ]
