# Generated by Django 5.1.3 on 2024-11-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_datarow_unique_scheme_per_head'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datarow',
            name='unique_scheme_per_head',
        ),
        migrations.AddConstraint(
            model_name='datarow',
            constraint=models.UniqueConstraint(fields=('scheme_name',), name='unique_scheme_name'),
        ),
        migrations.AddConstraint(
            model_name='datarow',
            constraint=models.UniqueConstraint(fields=('head_name',), name='unique_head_name'),
        ),
    ]
