# Generated by Django 5.1.3 on 2024-11-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_datarow_unique_scheme_per_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarow',
            name='divisible',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
