# Generated by Django 5.1.3 on 2024-11-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_datarow_in_divisible'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarow',
            name='in_divisible',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
