# Generated by Django 5.1.3 on 2024-11-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_datarow_in_divisible'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarow',
            name='divisible',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
