# Generated by Django 5.1.3 on 2024-11-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_datarow_agreed_by_fd'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarow',
            name='excess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='datarow',
            name='surrender',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='datarow',
            name='variation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='datarow',
            name='agreed_by_fd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
