# Generated by Django 5.1.3 on 2024-11-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_datarow_excess_datarow_surrender_datarow_variation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarow',
            name='agreed_by_fd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
