# Generated by Django 5.1.3 on 2024-11-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_datarow_agreed_by_fd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarow',
            name='excess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datarow',
            name='surrender',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datarow',
            name='variation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
