# Generated by Django 5.1.3 on 2024-11-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_datarow_excess_alter_datarow_surrender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarow',
            name='scheme_name',
            field=models.CharField(max_length=150),
        ),
    ]
