# Generated by Django 5.1.3 on 2024-12-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_datarow_scheme_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarow',
            name='last_change_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
