# Generated by Django 5.1.3 on 2024-12-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_datarow_last_change_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarow',
            name='last_change_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
