# Generated by Django 5.1.3 on 2024-12-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_alter_datarow_last_change_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarow',
            name='sanctioned_budget',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
