# Generated by Django 5.1.4 on 2025-02-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_datarow_sanctioned_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarow',
            name='head_type',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
